name: Ubuntu RDP with XRDP and Ngrok

on:
  workflow_dispatch:  # run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install XRDP and Desktop Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp xfce4 xfce4-goodies
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Download and Setup Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin/

      - name: Authenticate Ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok Tunnel for RDP (Port 3389)
        run: |
          nohup ngrok tcp 3389 --region=us > ngrok.log &

      - name: Show Ngrok URL
        run: |
          sleep 5
          cat ngrok.log
          curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
